export const profilesApi = [
  {
    id: 1,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
  {
    id: 2,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
  {
    id: 3,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
  {
    id: 4,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
  {
    id: 5,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
  {
    id: 6,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
  {
    id: 7,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
  {
    id: 8,
    name: 'Danilo Sampaio',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 984626807',
    email: 'daniloarpesam@gmail.com',
    place: 'São Paulo',
  },
]