export const profilesApi = [
  {
    id: 1,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 2,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 3,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 4,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 5,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 6,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 7,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 8,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 9,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 10,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 11,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
  {
    id: 12,
    name: 'Great Forest Gump',
    position: 'Desenvolvedor Full Stack',
    area: 'Tecnologia',
    phone: '11 999999999',
    email: 'emailemail@email.com',
    place: 'São Paulo',
  },
]